name: "Build applicable branches on push or pull request"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 1.* branches
on:
  push:
    branches: [ "1.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Remove any generated assets/data
        run: rm -rf ./src/generated
      - name: Generate assets & data
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runData --no-daemon
      - name: Validate assets
        run: test -d ./src/generated -a -f ./src/generated/resources/.cache/cache
      - name: Build JAR
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Set up mod metadata
        id: mod_meta
        run: |
          echo mc_version=$(grep ^mc_version ./gradle.properties | cut -d= -f2) >> $GITHUB_OUTPUT
      - name: Publish to Modmaven
        uses: gradle/gradle-build-action@v2
        env:
          MODMAVEN_USER: ${{ secrets.MODMAVEN_USER }}
          MODMAVEN_PASSWORD: ${{ secrets.MODMAVEN_PASSWORD }}
        with:
          arguments: publishMavenPublicationToModmavenRepository --no-daemon
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if:
          env.DISCORD_WEBHOOK != null
        with:
          args: 'Build complete for project {{ EVENT_PAYLOAD.repository.full_name }} (Minecraft ${{ steps.mod_meta.outputs.mc_version}}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.'
